name: github_sample
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  dio: ^5.0.3
  flutter_riverpod: ^2.0.0
  equatable: ^2.0.3
  sqflite: ^2.0.0+4
  path: ^1.8.0
  path_provider: ^2.0.9
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.9
  flutter_dotenv: ^5.0.2

dev_dependencies:
  test: ^1.16.0
  mockito: ^5.0.17
  build_runner: ^2.0.6
  sqflite_common_ffi: ^2.0.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/